#!/bin/bash
echo "🚀 AiSH 태스크 관리 시스템 - 간단 배포 가이드"
echo ""
echo "=== 가장 쉬운 방법: Railway 배포 ==="
echo "1. https://railway.app 접속"
echo "2. 'Login with GitHub' 클릭" 
echo "3. 'New Project' → 'Deploy from GitHub repo' 선택"
echo "4. 리포지토리 선택: safe1124/coding-test"
echo "5. 'Deploy Now' 클릭"
echo "6. 완료! 자동으로 URL이 생성됩니다"
echo ""
echo "=== Railway 장점 ==="
echo "✅ GitHub 연동만으로 3분 배포"
echo "✅ SSL 인증서 자동 설정"  
echo "✅ 커밋할 때마다 자동 재배포"
echo "✅ 무료 플랜 $5/월 크레딧 제공"
echo ""
echo "=== 구글 클라우드가 원하시면 ==="
echo "아래 명령어로 GCP 배포도 가능합니다:"
echo "bash deploy-gcp.sh"
