#!/bin/bash
echo "🌐 Google Cloud Platform 배포 가이드"
echo ""
echo "=== 1단계: GCP 계정 및 프로젝트 설정 ==="
echo "1. https://cloud.google.com 접속"
echo "2. '무료로 시작하기' 클릭 ($300 크레딧 제공)"
echo "3. 새 프로젝트 생성: 'aish-tasks-system'"
echo "4. 결제 계정 연결 (무료 크레딧 사용)"
echo ""
echo "=== 2단계: Cloud Shell에서 실행할 명령어들 ==="
echo "# Cloud Shell 열기 (브라우저 내 터미널)"
echo "git clone https://github.com/safe1124/coding-test.git"
echo "cd coding-test"
echo ""
echo "# Cloud Run 배포"
echo "gcloud run deploy aish-tasks \\"
echo "  --source . \\"
echo "  --region asia-northeast1 \\"
echo "  --allow-unauthenticated \\"
echo "  --port 8600"
echo ""
echo "=== 3단계: 배포 완료! ==="
echo "✅ 자동으로 HTTPS URL 생성"
echo "✅ 전세계 어디서나 접속 가능"
echo "✅ 사용한 만큼만 과금 (월 $1-5 예상)"
echo ""
echo "❗ 주의: Railway가 더 간단하니 그쪽을 추천합니다!"
