[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

# Next.js 앱용 redirects
[[redirects]]
  from = "/api/*"
  to = "https://unique-perception-production.up.railway.app/:splat"
  status = 200
  force = true

# Next.js SPA 라우팅 지원
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, PATCH, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, Accept, Authorization"
