[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile.backend-only"

[deploy]
startCommand = "python backend/run_server.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300

[build.environment]
NODE_OPTIONS = "--max-old-space-size=256"
PIP_TIMEOUT = "600"
PIP_RETRIES = "5"
PYTHONOPTIMIZE = "1"
PYTHONDONTWRITEBYTECODE = "1"
PIP_NO_CACHE_DIR = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"
RAILWAY_DOCKERFILE = "Dockerfile.backend-only"

[deploy.environment]
PYTHONOPTIMIZE = "1"
PYTHONDONTWRITEBYTECODE = "1"
PIP_NO_CACHE_DIR = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"
