[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.ultra-light"

[deploy]
startCommand = "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300

[build.environment]
NODE_OPTIONS = "--max-old-space-size=512"
PIP_TIMEOUT = "300"
PIP_RETRIES = "3"
