"""start engineering

Revision ID: e53fa7c502f6
Revises: 6cb24c9f1da9
Create Date: 2024-11-22 22:15:15.832596+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e53fa7c502f6'
down_revision: Union[str, None] = '6cb24c9f1da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_table')
    op.drop_index('ix_chat_log_id', table_name='chat_log')
    op.drop_table('chat_log')
    op.add_column('user_table', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('user_table', sa.Column('name', sa.String(), nullable=False))
    op.add_column('user_table', sa.Column('mail', sa.String(), nullable=False))
    op.add_column('user_table', sa.Column('password', sa.String(), nullable=False))
    op.drop_constraint('user_table_user_mail_key', 'user_table', type_='unique')
    op.create_unique_constraint(None, 'user_table', ['mail'])
    op.drop_column('user_table', 'user_id')
    op.drop_column('user_table', 'user_name')
    op.drop_column('user_table', 'user_mail')
    op.drop_column('user_table', 'user_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('user_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_table', sa.Column('user_mail', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_table', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_table', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_table', type_='unique')
    op.create_unique_constraint('user_table_user_mail_key', 'user_table', ['user_mail'])
    op.drop_column('user_table', 'password')
    op.drop_column('user_table', 'mail')
    op.drop_column('user_table', 'name')
    op.drop_column('user_table', 'id')
    op.create_table('chat_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.user_id'], name='chat_log_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_log_pkey')
    )
    op.create_index('ix_chat_log_id', 'chat_log', ['id'], unique=False)
    op.create_table('role_table',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_role', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('admin_role', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.user_id'], name='role_table_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='role_table_pkey')
    )
    # ### end Alembic commands ###
